<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="style.css">
    <title>Administration</title>
</head>
<body>
   <!-- nav bar  -->
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Aws Cinéma</a> 
   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="home.php">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="administration.php">Administration</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="mailto:rayenmohamed2310@gmail.com">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>  
<div class="container d-flex justify-content-center mt-5 py-5">
  <div class="col-xl-10 py-1 ">
    <div class="row shadow-lg rounded p-5">
         <div class="col-lg-6 mt-2" >
         <form class="admin" action="administration.php"   method="POST"> 
  <?php if(array_key_exists('msg',$_GET)):?> 
      <div class="alert alert-danger">
         <?=$_GET['msg']?>
      </div>
  <?php endif; ?>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
  </div>
  <button type="submit" name="login" class="btn btn-primary" ><i class="bi bi-door-open"></i>LogIn</button>
  <button type="Reset" class="btn btn-danger"><i class="bi bi-box-arrow-right"></i>Cancel</button>
</form>
         </div>
         <div class="col-lg-6">
            <img class="d-lg-block d-none" src="./media/hero-img.png" widt="100%" height="100%" alt="">
         </div>
    </div>
    </div>
</div>
   
</div>

</body>
</html>