<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="style.css">
    <title>Home</title>
</head>
<body>


<!-- nav bar -->
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Aws Cinéma</a>
   <span> <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"></span>
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="home.php">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="administration.php">Administration</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="mailto:rayenmohamed2310@gmail.com">Contact</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
      </form>
    </div>
  </div>
</nav>

<?php include 'search.php' ?>
<div class="container d-flex justify-content-center mt-5 py-5">
  <div class="row-xl-10 py-1 ">
    <div class="col shadow-lg rounded p-5">
         <div class="row-lg-6 mt-2" >
         <a href="acheterTicket.php"> <button type="button"  class="btn btn-outline-primary px-5 mt-2" id="buy"><i class="bi bi-bag-fill"></i> Acheter ticket</button></a>
         <?php foreach($films as $film) :?>
         <form class="admin" action="acheterTicket.php"   method="POST"> 
         <input type="hidden" name="id" value='<?=isset($_GET['id']) ? $_GET['id'] : ''?>'>
              <div class="mb-4">
               <h5>Nom Film :</h5>
                 <?= $film['nom_film'] ?>
              </div> 
              <div class="mb-3">
                <h5> Un film de </h5>
                    <?= $film['realisateur'] ?>
              </div>
              <div>
              <h5> Date de projection et heure de projection</h5>
                    <?= $film['date'] ?> <br>
                    <?=$film['heure_projection']?>
              </div>
              <div>
              <h5> Nombre de plaçes disponibles :</h5>
                    <?= $film['nbr_places'] ?> <br>
              </div>
             <!-- <a href="acheterTicket.php?id=<?=$film['id_film'] ?>"> <button type="button"  class="btn btn-outline-primary px-5 mt-2" id="buy"><i class="bi bi-bag-fill"></i> Acheter ticket</button></a> -->
              </form>
              <?php endforeach;?>
         </div>       
         </div>
      </div>
    </div>
</div>   
</div>
</body>
</html>