<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="style.css">

    <title>Mise à jour</title>
</head>
<body>
  <!-- nav bar -->
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Aws Cinéma</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="home.php">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="administration.php">Administration</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="mailto:rayenmohamed2310@gmail.com">Contact</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="button">Search</button>
      </form>
    </div>
  </div>
</nav>  


<form action="update.php" method="POST" class="row g-3 m-5" name="f">
  <input type="hidden" name="id" value='<?=isset($_GET['id']) ? $_GET['id'] : ''?>'>
  <div class="col-md-6">
    <label for="inputEmail4" class="form-label" >Nom film</label>
    <input type="text" class="form-control" id="inputEmail4" name="nom" value="<?=$film['nom_film']?>">
  </div>
  <div class="col-md-6">
    <label for="inputPassword4" class="form-label">Realisateur</label>
    <input type="text" class="form-control" id="inputPassword4" name="realisateur" value='<?=$film['realisateur']?>'>
  </div>
  <div class="col-12">
    <label for="inputAddress" class="form-label">type</label>
    <input type="text" class="form-control" id="inputAddress" placeholder="" name="type" value='<?=$film['type']?>'>
  </div>
  <div class="col-12">
    <label for="inputAddress2" class="form-label">description</label>
    <input type="text" class="form-control" id="inputAddress2"  name="description" value='<?=$film['description']?>'>
  </div>
  <div class="col-md-6">
    <label for="inputCity" class="form-label">Date</label>
    <input type="date" class="form-control" id="inputCity" name="date" value="<?=$film['date']?>">
  </div>
  
  <div class="col-md-2">
    <label for="inputZip" class="form-label">Nombre de place</label>
    <input type="text" class="form-control" id="inputZip" name="nbr_places" value='<?=$film['nbr_places']?>'>
  </div>
  <div class="col-md-2">
    <label for="inputZip" class="form-label">Heure de projection</label>
    <input type="time" class="form-control" id="inputZip" name="heure_projection" value='<?=$film['heure_projection']?>'>
  </div>

  <div class="col-md-2">
    <label for="inputZip" class="form-label">date realisation</label>
    <input type="date" class="form-control" id="inputZip" name="daterealisation" value='<?=$film['daterealisation']?>'>
  </div>

  <div class="col-12">
  <button type="submit" name="edit" class="btn btn-success"><i class="bi bi-pencil-square"></i> Mise à jour</button>
    <button type="reset" class="btn btn-danger"><i class="bi bi-calendar-x-fill"></i> Supprimer</button>
  </div>
</form>
</body>
</html>